---
- name: builidng a docker image ad push to dockerhub
  hosts: localhost 
  tasks:
  - name: Build_Docker_image
    docker_image:
      path: "/home/ansible/test_proj"
      name: "testimage"
     #      repository: "962093/dcker_spring_test:v3"
  - name: Push to docker hub
    docker_image:
      name: "testimage"
      push: yes
  - name: Removing unused images
    docker_image:
      name: "testimage"  
      state: absent
  
       
      
             
      
