apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8585
    targetPort: 8585
    protocol: TCP
  selector:
    name: sts-app-pod
    app: springboot-app
