apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  ports:
  - port: 8585
    targetPort: 8585
    nodePort: 30007
  selector:
    name: sts-app-pod
    app: springboot-app
